language: php

php:
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: 8.0

services:
  - mysql
  - memcached
  - redis
  - postgresql

before_install:
#  - composer global require phpunit/phpunit ^8.0||^9.0 --ignore-platform-reqs
  - sh -e build/travis/scripts/libsodium.sh

#install:
#  - printf "n\nn\nn\nn\n" | pecl install swoole

before_script:
  - sh -e build/travis/scripts/pecl-libsodium.sh || true
  - composer install --ignore-platform-reqs
#  - phpenv rehash

script:
  - php -S localhost:8100 bin/test-server.php &> /dev/null &
  - php vendor/bin/phpunit --configuration phpunit.travis.xml
