language: php

sudo: true
dist: trusty

php:
  - '7.1'
  - '7.2'
  - '7.3'

addons:
  postgresql: "9.3"

services:
  - memcached # will start memcached

before_install:
  - composer self-update
  - sh -e build/travis/scripts/apt-get.sh
  - sh -e build/travis/scripts/apache2-vhost.sh
  - sh -e build/travis/scripts/apache2-configure.sh
  - sudo add-apt-repository ppa:ondrej/php -y
  - sh -e build/travis/scripts/libsodium.sh

before_script:
  - curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
  - chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit
  - sh -e build/travis/scripts/pecl-libsodium.sh || true
  - composer update
  - phpenv rehash

script:
  - phpunit --configuration phpunit.travis.xml
